### ISSUE TITLE
As a user I can mark a task as done

### ISSUE THREAD

**Issue by shixiyue** [CS2103AUG2016-F10-C4/main#13]
...so that I can monitor my task progression

**Comment by LiXiaoooowei** [comment]
-need to update storage about those tasks being marked as done
-need to reflect the task status (done) on the gui

**Comment by shixiyue** [comment]
Progress: 
- update storage about those tasks being marked as done
- reflect the task status on the gui
- list done and undone

Todo:
- update test cases
