### ISSUE TITLE
Feedback for code quality of A0142325R

### ISSUE THREAD

**Issue by chanjunweimy** [CS2103AUG2016-F10-C4/main#40]
# main
- You should apply SLAP more. For example, the method below is very long and should be refactored:
  ![image](https://cloud.githubusercontent.com/assets/7464833/19830715/2925bd4c-9e30-11e6-80ee-65bcd53eae99.png)
- You need to write more header comments.
- Be careful of the coding standards violation such as: (the spacing)
  ![image](https://cloud.githubusercontent.com/assets/7464833/19830731/5c656892-9e30-11e6-944b-eb51027eb16c.png)
# test
- You might want to separate long test methods to multiple test methods or apply SLAP:
  ![image](https://cloud.githubusercontent.com/assets/7464833/19830921/f66302ec-9e30-11e6-9257-c75301edb3aa.png)
- Note that there is a test method naming convention and make sure yourself to follow it: (this is an example of violation case)
  ![image](https://cloud.githubusercontent.com/assets/7464833/19830925/1c565102-9e31-11e6-9010-8502ea270636.png)
# doc

No comment

Generally, good job :D

**Comment by LiXiaoooowei** [comment]
i have just refactored my test and main classes, thank you for pointing out
